import { SessionCard } from "@/components/session-card";
import type { SessionPlan } from "@/lib/types";

// Demo session — will be generated by the planner / Claude
const demoSession: SessionPlan = {
  date: "2026-03-16",
  training_block: "Hypertrophy Block 1",
  week_number: 1,
  is_deload: false,
  readiness_score: "HIGH",
  readiness_reasoning: [
    { signal: "HRV", value: 74, baseline: "57 ± 4.5", deviation: "+3.8 SD", tier_assigned: "HIGH" },
    { signal: "RHR delta", value: 0, tier_assigned: "HIGH" },
    { signal: "Sleep", value: 7, tier_assigned: "HIGH" },
  ],
  pill_phase: "active",
  session_type: "strength_lower",
  location: "home_gym",
  warmup: "5 min treadmill walk → leg swings, hip circles, bodyweight squats (10 each) → 1 set goblet squat @ 15 lbs × 10",
  exercises: [
    { name: "Goblet Squat", target_area: "quads, glutes", sets: 3, reps: "8", load: "30 lb DB", rest_seconds: 90, rpe_target: 7, notes: "Advanced from 25 lbs. Reset reps to 8." },
    { name: "Sumo Squat", target_area: "adductors, glutes", sets: 3, reps: "10–12", load: "25 lb DB", rest_seconds: 90, rpe_target: 7, notes: "NEW — assessment. Find working weight." },
    { name: "Romanian Deadlift", target_area: "hamstrings, glutes", sets: 3, reps: "12", load: "25 lbs ea", rest_seconds: 90, rpe_target: 7, notes: "Pushing to top of rep range before load increase." },
    { name: "Hip Thrust", target_area: "glutes", sets: 3, reps: "13–15", load: "35 lbs ea", rest_seconds: 90, rpe_target: 7, notes: "Building reps toward 15 before 40 lb jump." },
    { name: "Hanging Leg Raise", target_area: "lower abs", sets: 3, reps: "12", load: "BW", rest_seconds: 45, notes: "When easy, add ankle weights." },
    { name: "Dead Bug", target_area: "deep core", sets: 3, reps: "10 ea side", load: "BW", rest_seconds: 30 },
    { name: "Stomach Vacuum", target_area: "TVA", sets: 3, reps: "15 sec hold", load: "—", rest_seconds: 30, notes: "Progressed from 10 sec." },
  ],
  focus_cue: "Control the bottom of every squat and hinge — 2 sec pause at the stretch, then drive up.",
  estimated_duration_minutes: 50,
  progression_note: "Goblet squat advances 25→30 lbs (hit 3×12 at RPE ~7 on Mar 13). RDL pushing to top of rep range. Sumo squat is new — assess weight. Vacuum hold extended to 15 sec.",
  nutrition_note: "Get 25–30g protein within an hour after.",
};

export default function SessionPage() {
  return (
    <div className="py-6">
      <div className="mb-6">
        <h1 className="text-2xl font-bold text-zinc-100">Session Plan</h1>
        <p className="text-sm text-zinc-500 mt-1">
          Today&apos;s workout based on your readiness and progression.
        </p>
      </div>
      <SessionCard plan={demoSession} />
    </div>
  );
}
